name: test_bqplot_voici
channels:
  - conda-forge
dependencies:
  - astropy
  - bqplot
  - ipysheet
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - micromamba
  - numpy
  - pandas
  - python
  - pythreejs
  - traitlets
  - voila
  - voici
